### ISSUE TITLE
Before you get too far in

### ISSUE THREAD

**Issue by johnroper100** [ChristianGaertner/dmx-controller#1]
Hi, I just stumbled upon your project and wanted to share a very similar project that I have been working on for a long time. [https://github.com/johnroper100/Tonalite](https://github.com/johnroper100/Tonalite)

I don't know what your exact goals are, but if they are like my project, I wanted to share my link before you got too far into development when it isn't necessary to do so.

**Comment by ChristianGaertner** [comment]
Hey, thanks for reaching out! Your project looks indeed similar to some degree and uses the same idea. But I want to focus this project on automated light shows (be able to use it without having a dedicated light designer/operator on site) and less on replacing manually operated consoles.
